<?php
####要設定
$includePath="../user/twitter/phpmodules";
$dbpath="../user/twitter/data/favtw.db3";
$cachepath="../user/twitter/data/favtwcache.tmp";
$consumerKey='Uv3yBFQmb8b2CX86jTjWpA';
$consumerSecret='m2Ifqcyd9E8ztT3gwVgvRd9xLPseRK4axzwek5QMec';
$accessToken='399831056-CifFQh17HawWLUQk2vjdVNKqPG2xWFUQ2IkeBlCM';
$accessTokenSecret='979BriOeBLWO2qgYDzF1uoUCcM5ElWdOlQCZmHmVmCY';
?>
